const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),XLSX=require('xlsx');
const ctx={window:{XLSX},XLSX,console},base=path.resolve(__dirname,'..');vm.createContext(ctx);
for(const n of ['parser','parser-status','reports','parser-auto','adapters','data-integrity','analytics','privacy','insights','rules','schedule','compute-logic','exporters'])vm.runInContext(fs.readFileSync(base+'/assets/js/'+n+'.js','utf8'),ctx);
const head=['الاجمالي','الضريبة','الخصم','السعر','الكمية','الخدمة','طريقة الحجز','شركة التامين','المريض','ملف المريض','الطبيب','تاريخ الحجز'];
const rows=[head,[100,0,0,100,1,'كشف','Clinic','جهة تسعير','مريض تجريبي',1,'طبيب تجريبي','01-09-2026'],[50,0,0,50,1,'خدمة، بمستلزمات',null,null,null,null,null,null],[150],[0,0,100,100,1,'خدمة مجانية','Clinic','','مريض ثان',2,'طبيب ثان','02-09-2026'],[0],[150]];
const wb=XLSX.utils.book_new(),sheet=XLSX.utils.aoa_to_sheet(rows);sheet['!merges']=[6,7,8,9,10,11].map(c=>({s:{r:1,c},e:{r:2,c}}));XLSX.utils.book_append_sheet(wb,sheet,'statusstatmentReport');
XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Column1'],['الاجمالي'],[150]]),'عرض إضافي');
const result=ctx.window.SonoComputeLogic.execute('parseReport',{buffer:XLSX.write(wb,{type:'array',bookType:'xlsx'}),fileName:'statusstatmentReport.xlsx'});
assert.equal(result.kind,'report');assert.equal(result.datasets.length,1);const ds=result.datasets[0];assert.equal(ds.id,'statusDetail');assert.equal(ds.rows.length,3);assert.equal(ds.rows[1].date,'2026-09-01');assert.equal(ds.rows[1].insurer,'جهة تسعير');assert.equal(ds.rows[2].insurer,null);assert.equal(ds.warnings.length,0);
const adapted=ctx.window.SonoAdapters.apply(result.datasets),merged=ctx.window.SonoDataIntegrity.mergeSources(adapted.sources);const A=ctx.window.SonoAnalytics.analyze(merged.income,[],{});A.ins=ctx.window.SonoPrivacy.insights(ctx.window.SonoInsights.build(result.datasets,{}));const E=ctx.window.SonoRules.evaluate(A,null);
assert.equal(A.kpi.revenue,150);assert.equal(A.kpi.lineItems,3);assert.equal(A.kpi.patients,2);assert.equal(A.kpi.receipts,2);assert.equal(A.kpi.net,null);assert.equal(A.kpi.margin,null);assert.equal(A.kpi.cashShare,null);assert.equal(E.score,null);assert(!E.risks.some(r=>['supplies','margin','costRatio'].includes(r.id)));assert.equal(merged.income.filter(r=>r.amount===0).length,1);assert.equal(merged.income[1].services.length,1);assert.equal(merged.income[0].method,'غير محدد');
// Unmerged blanks must stay blank, not inherit a previous person's insurer or channel.
const unmerged=ctx.window.SonoAuto.parseAll({SheetNames:['s'],Sheets:{s:XLSX.utils.aoa_to_sheet(rows)}},'statusstatmentReport.xlsx')[0];assert.equal(unmerged.rows[1].insurer,null);assert.equal(unmerged.rows[1].date,null);
const mismatched=XLSX.utils.aoa_to_sheet([...rows.slice(0,-1),[999]]);assert.equal(ctx.window.SonoAuto.parseAll({SheetNames:['s'],Sheets:{s:mismatched}},'statusstatmentReport.xlsx')[0].warnings.length,1);
// Archive-compatible inputs without this source classification retain existing financial behavior.
const cash=ctx.window.SonoAnalytics.analyze([{...merged.income[0],_financialKind:'treasury',method:'نقدي'}],[],{});assert.equal(cash.kpi.net,100);assert.equal(cash.kpi.cashShare,1);
let book;ctx.XLSX.writeFile=b=>book=b;ctx.window.SonoExport.toXlsx(A,E,{clinic:'test',branch:'test'},result.datasets);const summary=XLSX.utils.sheet_to_json(book.Sheets['الملخص'],{header:1});assert.equal(summary.find(r=>r[0]==='الهامش الصافي')[1],'غير متاح');assert(!JSON.stringify(book).includes('مريض تجريبي'));
console.log('PASS detail vs summary detection, unlabeled totals, actual merges, blank insurer/channel, zero-net services, atomic service names, source reconciliation, unknown profit/payment metrics and private Excel export');
